### ISSUE TITLE
Can't run sample cases or submit from IDE

### ISSUE THREAD

**Issue by Rishabh510** [blueedgetechno/codeblue#3]

**Comment by blueedgetechno** [comment]
Can you explain the problem you are facing ...

**Comment by Rishabh510** [comment]
## Intitial setup:
![1](https://user-images.githubusercontent.com/42823059/102880625-a4189600-4471-11eb-90c1-9b8172a108c8.PNG)
## When running test cases: 
![2](https://user-images.githubusercontent.com/42823059/102880629-a5e25980-4471-11eb-99b6-32fb14d02852.PNG)
## When submitting solution
![3](https://user-images.githubusercontent.com/42823059/102880631-a67af000-4471-11eb-9966-a183dd86173c.PNG)

**Comment by blueedgetechno** [comment]
Verify the following steps:

1) Install online-judge-tools and fill the password in settings (if you want to submit from Atom IDE)
2) Disable "Beautify log error" in settings if you are not seeing code errors at all.

if you are still facing the problem, try pressing ctrl+shift+I, while taking the submit error screenshot which will give me more information about the error.

Thanks for using the plugin.

**Comment by Rishabh510** [comment]
Here is the console log
![2new](https://user-images.githubusercontent.com/42823059/102936106-8b3dce00-44cd-11eb-967f-d80811b97c65.PNG)

Even with beautify log errors as false and restarting Atom after clearing state, there is no difference.
![1new](https://user-images.githubusercontent.com/42823059/102936110-8c6efb00-44cd-11eb-9488-143e4f663f48.PNG)

**Comment by blueedgetechno** [comment]
try to submit from the command prompt

> oj s <problem_link> <your_file_path> --wait=0 --yes

**Comment by Rishabh510** [comment]
The developer has removed this feature a week ago. Refer [this PR](https://github.com/online-judge-tools/api-client/issues/127) for the same. Thanks a lot for making this plugin and handling my doubts.

**Comment by Rishabh510** [comment]
As far as running of sample cases is concerned. This is what the error is and I've run the command from command prompt its working fine as well from the package also A.exe file is created but still it is marked as error and doesn't proceed further.
![image](https://user-images.githubusercontent.com/42823059/103083176-c8a37800-4601-11eb-9127-6b65c3ea1252.png)

**Comment by Rishabh510** [comment]
> As far as running of sample cases is concerned. This is what the error is and I've run the command from command prompt its working fine as well from the package also A.exe file is created but still it is marked as error and doesn't proceed further.
> ![image](https://user-images.githubusercontent.com/42823059/103083176-c8a37800-4601-11eb-9127-6b65c3ea1252.png)

Well, I manually edited the file to increase the timeout from 2500 to 10000 and it worked and have added custom flags when compiling to avoid even more errors. Closing this issue.
